// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/explain-app.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var DESCRIPTION = `LocalGallery Pro \u2014 a privacy-first, "Zero-Cloud" Google Photos alternative.

Core rules:
- No third-party cloud storage for media (no Supabase Storage, Firebase, AWS, etc.).
- Photos and videos are routed to user-controlled destinations only:
    1. A local Node.js companion server on the user's PC / LAN.
    2. Telegram (user's own bot + chat id) via direct browser -> Telegram API calls.
    3. Browser File System Access API (direct local folder writes).
- All metadata (EXIF, favorites, archive, trash, provider config) lives in the browser's
  IndexedDB via Dexie.js. Actual file bytes are NEVER stored in IndexedDB.
- UI: dark theme, RTL Arabic, Google Photos-style masonry + timeline + lightbox,
  local EXIF extraction (exifr), and an inline SVG mini-map for GPS coordinates
  (no external map tiles).

This MCP server exposes a few stateless helper tools. It cannot read any given
end-user's browser IndexedDB \u2014 photo library data stays on the device.`;
var explain_app_default = defineTool({
  name: "explain_app",
  title: "Explain LocalGallery Pro",
  description: "Return a description of LocalGallery Pro, its Zero-Cloud policy, storage providers, and current features.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: DESCRIPTION }] })
});

// src/lib/mcp/tools/extract-exif.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
import exifr from "npm:exifr@^7.1.3";
var extract_exif_default = defineTool2({
  name: "extract_exif_from_url",
  title: "Extract EXIF from an image URL",
  description: "Fetch an image over HTTPS server-side and return the EXIF metadata (date taken, camera, lens, dimensions, GPS if present). The image bytes are not stored.",
  inputSchema: {
    url: z.string().url().describe("Publicly reachable HTTPS URL of an image (JPEG/HEIC/TIFF).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ url }) => {
    if (!/^https:\/\//i.test(url)) {
      return {
        content: [{ type: "text", text: "URL must start with https://" }],
        isError: true
      };
    }
    try {
      const res = await fetch(url);
      if (!res.ok) {
        return {
          content: [
            { type: "text", text: `Fetch failed: ${res.status} ${res.statusText}` }
          ],
          isError: true
        };
      }
      const buf = new Uint8Array(await res.arrayBuffer());
      const parsed = await exifr.parse(buf, { gps: true }) ?? {};
      const summary = {
        dateTaken: parsed.DateTimeOriginal ?? parsed.CreateDate ?? parsed.ModifyDate ?? null,
        make: parsed.Make ?? null,
        model: parsed.Model ?? null,
        lens: parsed.LensModel ?? parsed.LensMake ?? null,
        orientation: parsed.Orientation ?? null,
        width: parsed.ExifImageWidth ?? parsed.ImageWidth ?? null,
        height: parsed.ExifImageHeight ?? parsed.ImageHeight ?? null,
        iso: parsed.ISO ?? null,
        fNumber: parsed.FNumber ?? null,
        exposureTime: parsed.ExposureTime ?? null,
        focalLength: parsed.FocalLength ?? null,
        gps: parsed.latitude != null && parsed.longitude != null ? { latitude: parsed.latitude, longitude: parsed.longitude } : null
      };
      return {
        content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
        structuredContent: summary
      };
    } catch (err) {
      return {
        content: [
          {
            type: "text",
            text: `EXIF extraction failed: ${err.message}`
          }
        ],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/send-telegram-photo.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var send_telegram_photo_default = defineTool3({
  name: "send_telegram_photo",
  title: "Send a photo to Telegram",
  description: "Forward an image URL to Telegram's sendDocument API using the caller-provided bot token and chat id. The bot token is used only for this single request and is never stored server-side. This mirrors the direct browser -> Telegram flow the app uses.",
  inputSchema: {
    botToken: z2.string().min(10).describe("Telegram bot token from @BotFather. Used once, not stored."),
    chatId: z2.string().min(1).describe("Target chat id (e.g. your @userinfobot id, or a channel id)."),
    imageUrl: z2.string().url().describe("HTTPS URL of the image/document to send."),
    caption: z2.string().max(1024).optional().describe("Optional caption.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: true
  },
  handler: async ({ botToken, chatId, imageUrl, caption }) => {
    try {
      const url = `https://api.telegram.org/bot${botToken}/sendDocument`;
      const body = new URLSearchParams({
        chat_id: chatId,
        document: imageUrl,
        ...caption ? { caption } : {}
      });
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body
      });
      const json = await res.json();
      if (!json.ok) {
        return {
          content: [
            {
              type: "text",
              text: `Telegram error: ${json.description ?? "unknown"}`
            }
          ],
          isError: true
        };
      }
      const out = {
        ok: true,
        messageId: json.result?.message_id ?? null,
        chatId
      };
      return {
        content: [
          {
            type: "text",
            text: `Sent. message_id=${out.messageId ?? "?"} chat_id=${chatId}`
          }
        ],
        structuredContent: out
      };
    } catch (err) {
      return {
        content: [
          { type: "text", text: `Telegram request failed: ${err.message}` }
        ],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/generate-mock-photos.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function makeMockPhotos(count, seed = 0) {
  const now = Date.now();
  const day = 1e3 * 60 * 60 * 24;
  return Array.from({ length: count }, (_, i) => {
    const id = `mock-${seed}-${i}`;
    const width = 400 + i * 37 % 400;
    const height = 300 + i * 53 % 500;
    const date = new Date(now - i * day * 0.7).toISOString();
    return {
      id,
      name: `mock_${i + 1}.jpg`,
      width,
      height,
      date,
      thumbSrc: `https://picsum.photos/seed/${id}/${width}/${height}`
    };
  });
}
var generate_mock_photos_default = defineTool4({
  name: "generate_mock_photos",
  title: "Generate mock photos",
  description: "Return a deterministic list of placeholder photo entries (id, name, width, height, date, thumbSrc) matching the demo grid. Useful for testing gallery layouts.",
  inputSchema: {
    count: z3.number().int().min(1).max(200).default(24).describe("How many mock photos to return (1\u2013200)."),
    seed: z3.number().int().min(0).max(9999).default(0).describe("Seed to vary the generated set.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ count, seed }) => {
    const photos = makeMockPhotos(count, seed);
    return {
      content: [{ type: "text", text: JSON.stringify(photos, null, 2) }],
      structuredContent: { photos }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "localgallery-pro-mcp",
  title: "LocalGallery Pro MCP",
  version: "0.1.0",
  instructions: "Public helper tools for LocalGallery Pro \u2014 a privacy-first, Zero-Cloud photo gallery. Use `explain_app` for context, `extract_exif_from_url` to read image metadata, `send_telegram_photo` to forward an image URL to a user-supplied Telegram bot+chat, and `generate_mock_photos` to produce demo gallery data. This server is stateless and cannot read any user's local IndexedDB photo library.",
  tools: [explain_app_default, extract_exif_default, send_telegram_photo_default, generate_mock_photos_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
